### ISSUE TITLE
Can't open README

### ISSUE THREAD

**Issue by YaelinHam** [HugoLhuillier/IntroProg2018#6]
Dear @HugoLhuillier , 

1. I cloned the repo (easy)

`git clone https://github.com/git-game/git-game.git`

2. But then I can not open the README File ! :'(

```
cat README.md
No such file or directory
```
4. I also deleted my first attempt as follow (because I thought that I made a bug).

```
rm -rf https://github.com/git-game/git-game.git
git clone https://github.com/git-game/git-game.git
```

5. I went trought many forums, and one of them was talking about this download: 
[https://git-scm.com/download/mac](url)

Can it explain why is it not working ?

Thanks for your answer.

Yaelin

**Comment by HugoLhuillier** [comment]
Did you find out eventually? I believe it's because you were trying to read the `README.md` file from the wrong directory. If you: clone, __move into the directory__, and then `cat`, it should work. Like

```bash 
git clone https://github.com/git-game/git-game.git
cd git-game 
cat README.md
```
